spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: newvss
    password: yh2016
    url: jdbc:mysql://10.0.66.203:3306/newvss
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

swagger:
  enable: true

exclude:
  login:
   validate:
    path: /login
    key: 111111